// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaFotos.Web.Dados;

namespace SistemaFotos.Web.Migrations
{
    [DbContext(typeof(FotosContext))]
    [Migration("20200324190802_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SistemaFotos.Web.Models.Galeria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Data");

                    b.Property<string>("Descricao")
                        .IsRequired();

                    b.Property<string>("TituloDaGaleria")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Galerias");
                });

            modelBuilder.Entity("SistemaFotos.Web.Models.Imagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Caminho")
                        .IsRequired();

                    b.Property<int?>("GaleriaId");

                    b.Property<string>("Titulo")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("GaleriaId");

                    b.ToTable("Imagens");
                });

            modelBuilder.Entity("SistemaFotos.Web.Models.Imagem", b =>
                {
                    b.HasOne("SistemaFotos.Web.Models.Galeria", "Galeria")
                        .WithMany()
                        .HasForeignKey("GaleriaId");
                });
#pragma warning restore 612, 618
        }
    }
}
